kasir -> loginPage "Login dengan PIN"
admin -> loginPage "Login dengan PIN"
loginPage -> validatePin "Validasi PIN"
loginPage -> checkSession "Cek session"
validatePin -> authStore "Set session"
validatePin -> authLogin "IPC" "IPC: auth:login"
checkSession -> authStore "Validate token"
checkSession -> authCheckSession "IPC" "IPC: auth:check"
admin -> settingsPage "Konfigurasi aplikasi"
settingsPage -> settingsStore "Read/write settings"
settingsStore -> settingsWrite "IPC" "IPC: settings:*"